/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.form;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.WindowListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Mihailo
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        initPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserStatistics = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanelServerControls = new javax.swing.JPanel();
        btnStopServer = new javax.swing.JButton();
        btnStartServer = new javax.swing.JButton();
        lblServerStatus = new javax.swing.JLabel();
        jMenuBarMain = new javax.swing.JMenuBar();
        jmMovie = new javax.swing.JMenu();
        jmiNewMovie = new javax.swing.JMenuItem();
        jmiViewAllMovies = new javax.swing.JMenuItem();
        jmDirector = new javax.swing.JMenu();
        jmiNewDirector = new javax.swing.JMenuItem();
        jmiViewAllDirectors = new javax.swing.JMenuItem();
        jmActor = new javax.swing.JMenu();
        jmiNewActor = new javax.swing.JMenuItem();
        jmiViewAllActors = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jmiAboutSoftware = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblUserStatistics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "System role", "Collection size", "Review count", "Highest rated movie", "Score"
            }
        ));
        jScrollPane1.setViewportView(tblUserStatistics);

        jLabel1.setText("User statistics:");

        jPanelServerControls.setName("Server controls"); // NOI18N

        btnStopServer.setText("Stop server");
        btnStopServer.setEnabled(false);

        btnStartServer.setText("Start server");

        lblServerStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblServerStatus.setForeground(new java.awt.Color(255, 0, 0));
        lblServerStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServerStatus.setText("SERVER IS CLOSED");

        javax.swing.GroupLayout jPanelServerControlsLayout = new javax.swing.GroupLayout(jPanelServerControls);
        jPanelServerControls.setLayout(jPanelServerControlsLayout);
        jPanelServerControlsLayout.setHorizontalGroup(
            jPanelServerControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServerControlsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServerControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelServerControlsLayout.createSequentialGroup()
                        .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblServerStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelServerControlsLayout.setVerticalGroup(
            jPanelServerControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelServerControlsLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblServerStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelServerControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartServer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jmMovie.setText("Movie");

        jmiNewMovie.setText("New");
        jmMovie.add(jmiNewMovie);

        jmiViewAllMovies.setText("View all");
        jmMovie.add(jmiViewAllMovies);

        jMenuBarMain.add(jmMovie);

        jmDirector.setText("Director");

        jmiNewDirector.setText("New");
        jmDirector.add(jmiNewDirector);

        jmiViewAllDirectors.setText("View all");
        jmDirector.add(jmiViewAllDirectors);

        jMenuBarMain.add(jmDirector);

        jmActor.setText("Actor");

        jmiNewActor.setText("New");
        jmActor.add(jmiNewActor);

        jmiViewAllActors.setText("View all");
        jmActor.add(jmiViewAllActors);

        jMenuBarMain.add(jmActor);

        jMenuAbout.setText("About");

        jmiAboutSoftware.setText("Software");
        jMenuAbout.add(jmiAboutSoftware);

        jMenuBarMain.add(jMenuAbout);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelServerControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelServerControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartServer;
    private javax.swing.JButton btnStopServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JPanel jPanelServerControls;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jmActor;
    private javax.swing.JMenu jmDirector;
    private javax.swing.JMenu jmMovie;
    private javax.swing.JMenuItem jmiAboutSoftware;
    private javax.swing.JMenuItem jmiNewActor;
    private javax.swing.JMenuItem jmiNewDirector;
    private javax.swing.JMenuItem jmiNewMovie;
    private javax.swing.JMenuItem jmiViewAllActors;
    private javax.swing.JMenuItem jmiViewAllDirectors;
    private javax.swing.JMenuItem jmiViewAllMovies;
    private javax.swing.JLabel lblServerStatus;
    private javax.swing.JTable tblUserStatistics;
    // End of variables declaration//GEN-END:variables

    public void jmiNewMovieAddActionListener(ActionListener actionListener) {
        jmiNewMovie.addActionListener(actionListener);
    }

    public void jmiViewAllMoviesActionListener(ActionListener actionListener) {
        jmiViewAllMovies.addActionListener(actionListener);
    }
    
    public void jmiNewDirectorAddActionListener(ActionListener actionListener) {
        jmiNewDirector.addActionListener(actionListener);
    }
    
    public void jmiViewAllDirectorsActionListener(ActionListener actionListener) {
        jmiViewAllDirectors.addActionListener(actionListener);
    }
    
    public void jmiNewActorAddActionListener(ActionListener actionListener) {
        jmiNewActor.addActionListener(actionListener);
    }
    
    public void jmiViewAllActorsActionListener(ActionListener actionListener) {
        jmiViewAllActors.addActionListener(actionListener);
    }

    public JTable getTblUserStatistics() {
        return tblUserStatistics;
    }

    public JButton getBtnStartServer() {
        return btnStartServer;
    }

    public JButton getBtnStopServer() {
        return btnStopServer;
    }

    public JLabel getLblServerStatus() {
        return lblServerStatus;
    }
    
    public void btnStartServerActionListener(ActionListener actionListener) {
        btnStartServer.addActionListener(actionListener);
    }
    public void btnStopServerActionListener(ActionListener actionListener) {
        btnStopServer.addActionListener(actionListener);
    }
    
    public void frmMainWindowListener(WindowListener windowListener) {
        this.addWindowListener(windowListener);
    }

    private void initPanel() {
        Border border = BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black),"Server controls");
        jPanelServerControls.setBorder(border);
    }
}
